### ISSUE TITLE
xLabelAngle 

### ISSUE THREAD

**Issue by dAnK3L** [stewones/angular-morris-chart#49] opened 2016-04-06 14:21 UTC
Hi, i am trying to apply xLabelAngle on my bar chart which doesnt seem to work

bar-xLabelAngle=10

any help would be apprieciated.

**Comment by loren138** [comment] 2016-04-06 18:45
After #50 is merged and you update, you'll be able to use this with ``bar-x-label-angle="'90'"``.

**Comment by dAnK3L** [comment] 2016-04-07 07:38
thanks this worked :)

**Comment by dAnK3L** [comment] 2016-04-07 07:43
bar-chart
             bar-data="debtOverview"
             bar-x="DueDate"
             bar-x-label-angle="'50'"
             bar-y='["TyDecimal"]'
             bar-labels='["TY"]'
             bar-colors='["#1a96b4"]'
             bar-resize="true"
             bar-hide-hover="'auto'">

**Comment by stewones** [comment] 2016-04-07 12:53
Hi @dAnK3L 

it would be more easier to help if you try to reproduce your issue in tools like jsfidle.net and then share here

you can start by forking [this sample](https://jsfiddle.net/stewones/9zjasq3r/) and modifying it for your use case

**Comment by dAnK3L** [comment] 2016-04-07 13:54
Hi, i have updated the fiddle wth what i have with static data and the label doesn change angle..

https://jsfiddle.net/tqLgernc/

**Comment by loren138** [comment] 2016-04-07 15:39
It won't work until the pull request I tagged is merged because it isn't currently supported by this plugin. It looks like I made a mistake in my request though and I'm sick today so I can't go in to fix it. I should have time next Tuesday.

**Comment by dAnK3L** [comment] 2016-04-11 07:37
do you think this will be done soon? its really urgent for me

**Comment by loren138** [comment] 2016-04-11 19:06
I'll be back at work tomorrow. If you're using a js file, you could always temporarily use the version from #50.

**Comment by stewones** [comment] 2016-04-11 21:15
this feature is already implemented on master

https://github.com/stewones/angular-morris-chart/search?utf8=%E2%9C%93&q=xLabelAngle

**Comment by stewones** [comment] 2016-04-11 21:27
@dAnK3L 

checkout this sample https://jsfiddle.net/stewones/8apkc98c/

I'll close but feel free to reopen or ask anything

**Comment by loren138** [comment] 2016-04-11 22:51
This is a bar chart, it is implemented on line and area, but not bar.

**Comment by stewones** [comment] 2016-04-12 15:11
@loren138 :+1:

**Comment by stewones** [comment] 2016-04-12 18:05
fixed by #50 
thx @loren138

**Closed by stewones** 2016-04-12 18:05 UTC
Labels: 2doc, fixed-in-master
