### ISSUE TITLE
ng-click

### ISSUE THREAD

**Issue by goariel10** [stewones/angular-morris-chart#2] opened 2015-02-10 16:52 UTC
Hi, is there a way to handle ng-clicks inside chart elements? if so how could i do it  ? .......

**Comment by stewones** [comment] 2015-02-11 16:15
@goariel10 - what you mean about "inside chart elements" ? if you bind ng-click directly on directive, it should work. let me know if it does not.

**Comment by goariel10** [comment] 2015-02-13 17:58
![sample](https://cloud.githubusercontent.com/assets/6316096/6192440/94185614-b377-11e4-9b15-1c04564f374a.png)

**Comment by stewones** [comment] 2015-02-16 21:45
@goariel10 unfortunatly morris-chart does not support this trick
sorry.

**Comment by stewones** [comment] 2015-05-28 14:32
closing this since the morris.js does not support this kind of feature. but if anyone has any ideas , please PR.

**Closed by stewones** 2015-05-28 14:32 UTC

**Comment by Vahn84** [comment] 2015-07-24 09:43
It does support the hover feature though

It would be great if this kind of feature could have been reproduced as an ng-click in angularjs

**Comment by anupalhub** [comment] 2017-06-22 10:14
@Vahn84 How do we use it in Angular? Can we give custom $scope function?

**Comment by Vahn84** [comment] 2017-06-22 10:20
@anupalhub sorry mate, 2 years has passed, I don't really remember that T_T

**Comment by anupalhub** [comment] 2017-06-22 10:27
@st1s Any help ?

**Comment by stewones** [comment] 2017-06-23 14:33
Sorry guys, angularjs is deprecated. I will make the morris  module for angular 2 soon, what will be better to address issues like this
